mod_id=srpwarriorsarmaments
mod_name=Scape and Run: Warrior's Armaments
mod_group=com.sweeblyn.srpwarriorsarmaments
mod_version=v1.0
mod_author=["Sweeblyn"]
mod_description=An addon for SR:P that adds helpful anti-parasite gear
minecraft_version=1.12.2
forge_version=14.23.5.2860
mappings_channel=snapshot
mappings_version=20180814-1.12
mod_mixin_configs=mixins.${mod_id}.json
mod_mixin_refmap=refmap.${mod_id}.json
org.gradle.daemon=false
org.gradle.jvmargs=-Xmx3G
